### ISSUE TITLE
What version of python is required?

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/docs#35]
The docs aren't explicit about which version of Python is required. User told me:

> had Python 3.5 -- wasn't super clear that needed Python 3.7

This update should be made on https://docs.r2c.dev/en/latest/intro/installation.html

**Comment by ievans** [comment]
It should also be checked in the CLI and a clear message printed if we are below the minimum supported version

**Comment by dlukeomalley** [comment]
@ievans Linked in a sister ticket for tracking. Thanks!

**Comment by ulziibay** [comment]
We check 3.6 above in the CLI and error our accordingly in https://github.com/returntocorp/echelon-backend/blob/develop/r2c/cli/r2c/cli/commands/cli.py#L70. However, the CLI installation failed with python 3.5 or less. I think the best place to fix that is in the doc to specifically say 3.6 or above. See https://github.com/returntocorp/docs/pull/37 for fixing the doc
