### ISSUE TITLE
docs fails to build on readthedocs

### ISSUE THREAD

**Issue by pabloest** [returntocorp/docs#50]
Local building of the docs does build successfully, but docs fail to build on readthedocs with this error:

[Build #9451526](https://readthedocs.org/projects/r2c/builds/9451526/)
latest (63da493ea76fd9df1647b3b4a9b0827facc15a22)
Error
One or more submodule URLs are not valid: ['docs/pipelines/samples/typed-ast-rules-example'], git/ssh URL schemas for submodules are not supported.

It seems to me this is related to an issue in readthedocs: [Invalid submodule URL on public repositories #4043](https://github.com/readthedocs/readthedocs.org/issues/4043).
That issue is still open and based on the frequency of comments and updates about it, I don’t expect it to be fixed anytime soon.

A possible workaround would be to edit the repo URL and use `https` instead of `git@github.com` for the URL. But I’m not sure how to test this other than just trying it, pushing the update to readthedocs, and seeing if the build succeeds. Also, I’m not sure if changing the URL will break someone’s workflow as hinted at by [one of the comments](https://github.com/readthedocs/readthedocs.org/issues/4043#issuecomment-473558309) in the issue discussion.

@ievans since you made the change to the submodule in https://github.com/returntocorp/docs/commit/95686fb61b24e2d403c95d1928dd678cad6ab486, could you offer your opinion?

**Comment by ievans** [comment]
@pabloest not ideal, but switching to the https schema is probably the simplest method to fix.

Unless @DrewDennison would rather just host it all ourselves?

**Comment by DrewDennison** [comment]
fine to move to https instead of git@ (I think that's github rec anyway). I would **not** like to host it ourselves

**Comment by pabloest** [comment]
Thanks. OK I’ll make the change and submit a PR, then once approved try to build again.

**Comment by pabloest** [comment]
FYI readthedocs is successfully building our docs again. Thanks for your help.
